"""empty message

Revision ID: 062fa88b9638
Revises: ee340671a502
Create Date: 2022-04-03 13:18:19.161268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062fa88b9638'
down_revision = 'ee340671a502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
