"""movies table

Revision ID: ee340671a502
Revises: 06196da251a3
Create Date: 2022-04-03 10:29:45.262249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee340671a502'
down_revision = '06196da251a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('director', sa.String(length=128), nullable=True),
    sa.Column('cast', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('release_year', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('listed_in', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_date_added'), 'movies', ['date_added'], unique=False)
    op.create_index(op.f('ix_movies_director'), 'movies', ['director'], unique=False)
    op.create_index(op.f('ix_movies_duration'), 'movies', ['duration'], unique=False)
    op.create_index(op.f('ix_movies_listed_in'), 'movies', ['listed_in'], unique=False)
    op.create_index(op.f('ix_movies_release_year'), 'movies', ['release_year'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_type'), 'movies', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_type'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_release_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_listed_in'), table_name='movies')
    op.drop_index(op.f('ix_movies_duration'), table_name='movies')
    op.drop_index(op.f('ix_movies_director'), table_name='movies')
    op.drop_index(op.f('ix_movies_date_added'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
